name = "apaiptv"
type = "javascript"
main = "src/index.js"  # Asegúrate de que este archivo existe
compatibility_date = "2025-03-23"

[[kv_namespaces]]
binding = "HLS_SEQUENCE"
id = "75a2fa864dc244a582667fb7277cf22d"

[env.production.crons]
# Esto ejecuta la función cada 10 segundos.
# Se utiliza una expresión cron: "*/10 * * * *" -> cada 10 segundos
"*/10 * * * *" = "actualizarSecuencia"